name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  # Main CI job for testing and analysis
  test-and-analyze:
    name: Test & Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        cache: true
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Verify Flutter installation
      run: flutter doctor -v
      
    - name: Run code analysis
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Check code formatting
      run: dart format --set-exit-if-changed .

  # iOS build job
  ios-build:
    name: iOS Build
    runs-on: macos-latest
    needs: test-and-analyze
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        cache: true
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Build iOS app (no code signing)
      run: |
        flutter build ios --release --no-codesign
        
    - name: Archive iOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        path: build/ios/iphoneos/
        retention-days: 30