name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  # Main CI job for testing and analysis
  test-and-analyze:
    name: Test & Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        cache: true
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Verify Flutter installation
      run: flutter doctor -v
      
    - name: Run code analysis
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Check code formatting
      run: dart format --set-exit-if-changed .

  # iOS build job
  ios-build:
    name: iOS Build
    runs-on: macos-latest
    needs: test-and-analyze
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        cache: true
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Build iOS app (no code signing)
      run: |
        flutter build ios --release --no-codesign
        
    - name: Archive iOS build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-build-artifacts
        path: build/ios/iphoneos/
        retention-days: 30

  # Placeholder for future Android build
  # android-build:
  #   name: Android Build  
  #   runs-on: ubuntu-latest
  #   needs: test-and-analyze
  #   
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4
  #     
  #   - name: Setup Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: 'stable'
  #       cache: true
  #       
  #   - name: Get Flutter dependencies
  #     run: flutter pub get
  #     
  #   - name: Build Android APK
  #     run: flutter build apk --release
  #     
  #   - name: Archive Android build artifacts
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: android-build-artifacts
  #       path: build/app/outputs/flutter-apk/
  #       retention-days: 30

  # Placeholder for future Fastlane integration
  # deploy:
  #   name: Deploy to TestFlight
  #   runs-on: macos-latest
  #   needs: [test-and-analyze, ios-build]
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4
  #     
  #   - name: Setup Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: 'stable'
  #       cache: true
  #       
  #   - name: Setup Ruby for Fastlane
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: '3.0'
  #       bundler-cache: true
  #       working-directory: ios
  #       
  #   - name: Deploy to TestFlight via Fastlane
  #     run: |
  #       cd ios
  #       bundle exec fastlane beta
  #     env:
  #       APPLE_ID: ${{ secrets.APPLE_ID }}
  #       APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
  #       MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}